package vista;

import Modelo.Enfermedad;
import Modelo.Enfermero;
import Modelo.Historial;
import Modelo.Medico;
import Modelo.Paciente;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rrajo
 */
public class AñadirPaciente extends javax.swing.JFrame {

    private VistaEnfermeros vistaEnfermeros;
    private Enfermero enfermero;
    private ArrayList<Historial> historial;
    private LocalDate currentdate = LocalDate.now();
    
    private Paciente paciente;
    private DefaultListModel listaHistorialPacientes;
    /**
     * Creates new form AñadirPaciente
     */
    public AñadirPaciente(Enfermero enfermero ) {
        initComponents();
        this.enfermero = enfermero;
        
        this.diatext.setText(currentdate.getDayOfMonth()+"");
        this.mestext.setText(currentdate.getMonthValue()+"");
        this.anyoText.setText(currentdate.getYear()+"");
        this.textEnfermero.setText(enfermero.getApellidos() + ", "+enfermero.getNombre());
        
       
        
        DefaultComboBoxModel listaEnfermosModel = new DefaultComboBoxModel();
        ArrayList<Enfermedad> enfermedades_arrlist;
        try{
            enfermedades_arrlist = this.enfermero.getEnfermedades();
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(this, "No se ha encontrado la enfermedad", "Busqueda de enfermedad", JOptionPane.ERROR_MESSAGE);
            return;
        }        
        listaEnfermosModel.addAll(enfermedades_arrlist);
        enfermedadesCombox.setModel(listaEnfermosModel);
        
        DefaultComboBoxModel listaMedicosModel = new DefaultComboBoxModel();
        ArrayList<Medico> doctor_lista;
        try{
            enfermedades_arrlist = this.enfermero.getMedicos();
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(this, "No se ha encontrado el medico", "Busqueda de medico", JOptionPane.ERROR_MESSAGE);
            return;
        }        
        listaMedicosModel.addAll(enfermedades_arrlist);
        doctorCombox.setModel(listaMedicosModel);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDNI = new javax.swing.JLabel();
        textDNI = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelApellidos = new javax.swing.JLabel();
        textApellidos = new javax.swing.JTextField();
        labelEnfermedad = new javax.swing.JLabel();
        labelDoctor = new javax.swing.JLabel();
        labelEnfermero = new javax.swing.JLabel();
        textEnfermero = new javax.swing.JTextField();
        labelHabitacion = new javax.swing.JLabel();
        textHabitacion = new javax.swing.JTextField();
        botonExit = new javax.swing.JButton();
        botonAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diatext = new javax.swing.JTextField();
        mestext = new javax.swing.JTextField();
        anyoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        historialtext = new javax.swing.JTextArea();
        historialLabel = new javax.swing.JLabel();
        enfermedadesCombox = new javax.swing.JComboBox<>();
        doctorCombox = new javax.swing.JComboBox<>();
        buscarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDNI.setText("DNI");

        labelNombre.setText("Nombre");

        labelApellidos.setText("Apellidos");

        labelEnfermedad.setText("Enfermedad");

        labelDoctor.setText("Doctor");

        labelEnfermero.setText("Enfermero");

        textEnfermero.setEditable(false);

        labelHabitacion.setText("Habitacion");

        textHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHabitacionActionPerformed(evt);
            }
        });

        botonExit.setLabel("Salir");
        botonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExitMouseClicked(evt);
            }
        });
        botonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExitActionPerformed(evt);
            }
        });

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Dia:");

        jLabel2.setText("Mes:");

        jLabel3.setText("Año:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Añadir Paciente");

        diatext.setEditable(false);

        mestext.setEditable(false);

        anyoText.setEditable(false);

        historialtext.setEditable(false);
        historialtext.setColumns(20);
        historialtext.setRows(5);
        jScrollPane1.setViewportView(historialtext);

        historialLabel.setText("Historial Paciente");

        buscarPaciente.setText("Buscar");
        buscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHabitacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enfermedadesCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textDNI)
                            .addComponent(textNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(labelHabitacion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(labelEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(labelDoctor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(labelDNI))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(labelApellidos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(labelNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(buscarPaciente)))
                                .addGap(0, 14, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mestext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(diatext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelEnfermero)
                                                    .addComponent(anyoText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(23, 23, 23))
                                    .addComponent(botonAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(historialLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(botonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(historialLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(diatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mestext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(anyoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(botonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonExit)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(labelEnfermero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarPaciente)
                        .addGap(22, 22, 22)
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEnfermedad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enfermedadesCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(labelHabitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHabitacionActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:
        if(doctorCombox.getSelectedItem()==null)
            JOptionPane.showMessageDialog(this, "Selecciona un Doctor ", "Alta Paciente", JOptionPane.ERROR_MESSAGE);                
        else if(enfermedadesCombox.getSelectedItem()==null)
            JOptionPane.showMessageDialog(this, "Selecciona una Enfermedad ", "Alta Paciente", JOptionPane.ERROR_MESSAGE);                
        else if(textHabitacion.getText()== null)
            JOptionPane.showMessageDialog(this, "Selecciona una Habitación ", "Alta Paciente", JOptionPane.ERROR_MESSAGE);                
        else if(textDNI.getText() == null)
            JOptionPane.showMessageDialog(this, "Selecciona una DNI ", "Alta Paciente", JOptionPane.ERROR_MESSAGE);                
        else if(textNombre.getText() == null)
            JOptionPane.showMessageDialog(this, "Selecciona una Nombre ", "Alta Paciente", JOptionPane.ERROR_MESSAGE);                
        else if(textApellidos.getText() == null)
            JOptionPane.showMessageDialog(this, "Selecciona una Apellidos ", "Alta Paciente", JOptionPane.ERROR_MESSAGE); 
        else
        {
            Object aux = this.doctorCombox.getSelectedItem();
            Medico medico = (Medico) aux;
            paciente = enfermero.getDatosPaciente(this.textDNI.getText().trim());
            if(paciente == null)
            {
                paciente = new Paciente(0, this.textDNI.getText().trim(),  this.textNombre.getText(),
                                    this.textApellidos.getText(), 
                                    medico.getId(),
                                    enfermero.getId(), 
                                    currentdate.getDayOfMonth());
                LocalDate ahora = LocalDate.now();
                if(enfermero.darDeAltaNuevoPaciente(paciente, (Enfermedad)enfermedadesCombox.getSelectedItem() , ahora)){
                    JOptionPane.showMessageDialog(this, "PACIENTE AÑADIDO CORRECTAMENTE", "Alta Paciente", JOptionPane.INFORMATION_MESSAGE);
                    paciente = enfermero.getDatosPaciente(paciente.getDNI());
                    
                    if(enfermero.anyadirAlHistorial(paciente, (Enfermedad)enfermedadesCombox.getSelectedItem(), LocalDate.now()))
                        JOptionPane.showMessageDialog(this, "Historial añadido correctamente", "Alta Paciente", JOptionPane.INFORMATION_MESSAGE);
                    else
                        JOptionPane.showMessageDialog(this, "No se puede añadir entrada al historial del paciente", "Alta Paciente", JOptionPane.ERROR_MESSAGE); 
                }
                else
                    JOptionPane.showMessageDialog(this, "No se puede añadir entrada al historial del paciente", "Alta Paciente", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(enfermero.anyadirAlHistorial(paciente, (Enfermedad)enfermedadesCombox.getSelectedItem(), LocalDate.now()))
                    JOptionPane.showMessageDialog(this, "Historial añadido correctamente", "Alta Paciente", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this, "No se puede añadir entrada al historial del paciente", "Alta Paciente", JOptionPane.ERROR_MESSAGE); 
            }
            historial = paciente.getHistorial();
            String text="";
            for (Historial p: historial)
                text += p.toString() + "\n";

            this.historialtext.setText(text);
        }
       
    }//GEN-LAST:event_botonAñadirActionPerformed

    private void botonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonExitActionPerformed

    private void botonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseClicked
        vistaEnfermeros = new VistaEnfermeros(enfermero);
        vistaEnfermeros.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonExitMouseClicked

    private void buscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPacienteActionPerformed
        // TODO add your handling code here:
        
            paciente = enfermero.getDatosPaciente(this.textDNI.getText());
            if(paciente == null)
            {
                JOptionPane.showMessageDialog(this, "DNI no encontrado en la BD", "Alta Paciente", JOptionPane.ERROR_MESSAGE);                
            }
            else{
        
                textDNI.setText(paciente.getDNI());
                textApellidos.setText(paciente.getApellidos());
                textNombre.setText(paciente.getNombre());

                historial = paciente.getHistorial();

                String text="";
                for (Historial p: historial)
                    text += p.toString() + "\n";

                this.historialtext.setText(text);
            }
    }//GEN-LAST:event_buscarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anyoText;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonExit;
    private javax.swing.JButton buscarPaciente;
    private javax.swing.JTextField diatext;
    private javax.swing.JComboBox<String> doctorCombox;
    private javax.swing.JComboBox<String> enfermedadesCombox;
    private javax.swing.JLabel historialLabel;
    private javax.swing.JTextArea historialtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDoctor;
    private javax.swing.JLabel labelEnfermedad;
    private javax.swing.JLabel labelEnfermero;
    private javax.swing.JLabel labelHabitacion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField mestext;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textDNI;
    private javax.swing.JTextField textEnfermero;
    private javax.swing.JTextField textHabitacion;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
