/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Vista;

import java.util.Date;
import Modelo.Enfermero;
import Modelo.Gestor;
import Modelo.Medicamento;
import Modelo.Medico;
import Modelo.Paciente;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 *
 * @author rrajo
 */
public class AñadirPaciente extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer AñadirPaciente
     */
    public AñadirPaciente() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHabitación = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelEnfermedad = new javax.swing.JLabel();
        labelDoctor = new javax.swing.JLabel();
        labelEnfermero = new javax.swing.JLabel();
        textDNI = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        textEnfermedad = new javax.swing.JTextField();
        textDoctor = new javax.swing.JTextField();
        textEnfermero = new javax.swing.JTextField();
        textHbitacion = new javax.swing.JTextField();
        comboBoxDias = new javax.swing.JComboBox<>();
        comboBoxMes = new javax.swing.JComboBox<>();
        comboBoxAnyo = new javax.swing.JComboBox<>();
        labelDNI2 = new javax.swing.JLabel();
        botonExit = new javax.swing.JButton();
        botonAnyadirPaciente = new javax.swing.JButton();
        listaPacientes = new javax.swing.JScrollPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHabitación.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHabitación.setText("Habitación:");
        add(labelHabitación, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 70, -1));

        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFecha.setText("Fecha:");
        add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 50, -1));

        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombre.setText("Nombre:");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));

        labelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelApellidos.setText("Apellidos:");
        add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 50, -1));

        labelEnfermedad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEnfermedad.setText("Enfermedad:");
        add(labelEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 70, -1));

        labelDoctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDoctor.setText("Doctor:");
        add(labelDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, -1));

        labelEnfermero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEnfermero.setText("Enfermero:");
        add(labelEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, -1));

        textDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDNIActionPerformed(evt);
            }
        });
        add(textDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        add(textApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        add(textEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        textDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDoctorActionPerformed(evt);
            }
        });
        add(textDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        add(textEnfermero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        add(textHbitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        comboBoxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        comboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        comboBoxAnyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxAnyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        labelDNI2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDNI2.setText("DNI:");
        add(labelDNI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 30, -1));

        botonExit.setText("exit");
        botonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExitMouseClicked(evt);
            }
        });
        add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 50, -1));

        botonAnyadirPaciente.setText("Añadir Paciente");
        botonAnyadirPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnyadirPacienteMouseClicked(evt);
            }
        });
        add(botonAnyadirPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 40));
        add(listaPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 310, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void textDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDNIActionPerformed

    private void textDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDoctorActionPerformed

    private void botonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonExitMouseClicked

    private void botonAnyadirPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnyadirPacienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAnyadirPacienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnyadirPaciente;
    private javax.swing.JButton botonExit;
    private javax.swing.JComboBox<String> comboBoxAnyo;
    private javax.swing.JComboBox<String> comboBoxDias;
    private javax.swing.JComboBox<String> comboBoxMes;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelDNI2;
    private javax.swing.JLabel labelDoctor;
    private javax.swing.JLabel labelEnfermedad;
    private javax.swing.JLabel labelEnfermero;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHabitación;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JScrollPane listaPacientes;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textDNI;
    private javax.swing.JTextField textDoctor;
    private javax.swing.JTextField textEnfermedad;
    private javax.swing.JTextField textEnfermero;
    private javax.swing.JTextField textHbitacion;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
