/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Gestor;
import Data.Hospital;
import Modelo.Enfermero;
import Modelo.Medico;
import java.util.Date;

/**
 *
 * @author algar
 */
public class Login extends javax.swing.JFrame {

    private VistaMedico vistaMedico;
    private VistaEnfermeros vistaEnfermeros;
    private VistaGestor vistaGestor;
    private Medico medico;
    private Enfermero enfermero;
    private Gestor gestor;
    
    /**
     * Creates new form Vista
     */
    public Login(Medico medico, Enfermero enfermero, Gestor gestor) {
        this.medico = medico;
        this.enfermero = enfermero;
        this.gestor = gestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_medico = new javax.swing.JButton();
        btn_enfermero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_gestor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_medico.setText("Médico");
        btn_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medicoActionPerformed(evt);
            }
        });

        btn_enfermero.setText("Enfermero");
        btn_enfermero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enfermeroActionPerformed(evt);
            }
        });

        jLabel1.setText("Hospitalito");

        btn_gestor.setText("Gestor");
        btn_gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btn_medico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btn_enfermero)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_gestor)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_medico)
                    .addComponent(btn_enfermero))
                .addGap(18, 18, 18)
                .addComponent(btn_gestor)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medicoActionPerformed
        // TODO add your handling code here:
        vistaMedico = new VistaMedico(medico,enfermero, gestor);
        vistaMedico.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_medicoActionPerformed

    private void btn_enfermeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enfermeroActionPerformed
        // TODO add your handling code here:
        vistaEnfermeros = new VistaEnfermeros(medico,enfermero, gestor);
        vistaEnfermeros.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_enfermeroActionPerformed

    private void btn_gestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestorActionPerformed
        vistaGestor = new VistaGestor(medico, enfermero, gestor);
        vistaGestor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_gestorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        System.out.print("ESTOY EN EL MAIN");
        Hospital hospital = new Hospital();
        Medico medico= new Medico(hospital,1,"Manolo","García","34567812F","546993455",new Date());
        Enfermero enfermero= new Enfermero(1,"Manolo","García","34567812F","546993455",new Date(),hospital);
        Gestor gestor = new Gestor(hospital,1,"Manolo","García","34567812F","546993455",new Date());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(medico, enfermero, gestor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enfermero;
    private javax.swing.JButton btn_gestor;
    private javax.swing.JButton btn_medico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
