package Vista;

import Modelo.Gestor;
import Modelo.Enfermero;
import Modelo.Medico;
import Modelo.Paciente;
import java.time.LocalDate;
import java.util.ArrayList;
import Controlador.DAOpacientes;
import javax.swing.DefaultListModel;

/**
 *
 * @author ernes
 */
public class VistaEnfermeros extends javax.swing.JFrame {
    private BotiquinHospital vistaBotiquin;
    private Enfermero enfermero;
    private Paciente paciente;
    private LocalDate currentdate = LocalDate.now();
    private DefaultListModel<String> pacientesList;
    private ArrayList<Paciente> vpacientes;

    /**
     * Creates new form EnfermerosVista
     */
    public VistaEnfermeros(Enfermero enfermero) {
        initComponents();
        this.enfermero = enfermero;
        this.dia.setText(currentdate.getDayOfMonth()+"");
        this.txt_mes.setText(currentdate.getMonth()+"");
        this.txt_anyo.setText(currentdate.getYear()+"");
        pacientesList = new DefaultListModel<String>();
        
        vpacientes = Paciente.getAllPacientes();
        
                
        for(int i=0; i<vpacientes.size(); i++)
            pacientesList.addElement(vpacientes.get(i).getNombre());
        
        l_pacientes.setModel(pacientesList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_mes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_anyo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        l_pacientes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        BotiquinHospitalButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        anyadirPacienteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        lbl_hab = new javax.swing.JLabel();
        jtf_apellidos = new javax.swing.JTextField();
        jtf_hab = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dia:");

        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mes:");

        txt_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mesActionPerformed(evt);
            }
        });

        jLabel3.setText("Año:");

        txt_anyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anyoActionPerformed(evt);
            }
        });

        l_pacientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l_pacientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(l_pacientes);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Enfermeros");

        BotiquinHospitalButton.setText("Botiquín Hospital");
        BotiquinHospitalButton.setToolTipText("");
        BotiquinHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotiquinHospitalButtonActionPerformed(evt);
            }
        });

        SalirButton.setText("Salir");
        SalirButton.setToolTipText("");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        anyadirPacienteButton.setText("Añadir Paciente");
        anyadirPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyadirPacienteButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Lista Medicamentos:");

        lbl_apellidos.setText("Apellidos:");

        lbl_hab.setText("Habitación:");

        jtf_apellidos.setText("                     ");
        jtf_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_apellidosActionPerformed(evt);
            }
        });

        jtf_hab.setText("                     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_anyo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_apellidos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_hab))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_hab, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(SalirButton)
                .addGap(97, 97, 97)
                .addComponent(anyadirPacienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(BotiquinHospitalButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_anyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_apellidos)
                            .addComponent(lbl_hab)
                            .addComponent(jtf_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirButton)
                    .addComponent(anyadirPacienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotiquinHospitalButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void txt_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mesActionPerformed

    private void txt_anyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anyoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anyoActionPerformed

    private void BotiquinHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotiquinHospitalButtonActionPerformed
        // TODO add your handling code here:
        vistaBotiquin = new BotiquinHospital (enfermero);
        vistaBotiquin.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotiquinHospitalButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        // TODO add your handling code here:
        this.enfermero.launchMenu();
        dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void anyadirPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyadirPacienteButtonActionPerformed
        new AñadirPaciente(enfermero, paciente).setVisible(true);
        dispose();       
    }//GEN-LAST:event_anyadirPacienteButtonActionPerformed

    private void jtf_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_apellidosActionPerformed

    private void l_pacientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l_pacientesValueChanged
        int x = l_pacientes.getSelectedIndex();
        Paciente paciente = vpacientes.get(x);

        this.jtf_apellidos.setText(paciente.getApellidos());
        this.jtf_hab.setText(""+paciente.getHabitacion());

        
    }//GEN-LAST:event_l_pacientesValueChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotiquinHospitalButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JButton anyadirPacienteButton;
    private javax.swing.JTextField dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtf_apellidos;
    private javax.swing.JTextField jtf_hab;
    private javax.swing.JList<String> l_pacientes;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_hab;
    private javax.swing.JTextField txt_anyo;
    private javax.swing.JTextField txt_mes;
    // End of variables declaration//GEN-END:variables
}
